FROM alpine:latest  

MAINTAINER Alex Hong Pin Tan <alextan220990@gmail.com>

LABEL version="1.0.0"
LABEL description="A grpc-server serving events data"
LABEL language="golang:1.9"
LABEL keywords="go, grpc, grpc-server, event"

RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY app .
CMD ["./app"]