version: "3"
services:
  mongo: 
    image: mongo:3.4.9
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./mongo/:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_ROOT_PASSWORD}

  metabase:
    image: metabase/metabase
    ports:
      - 3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MD_DB_FILE=/metabase-data/metabase.db

  openzipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp # Accept zipkin.thrift over compact thrift protocol
      - 6831:6831/udp # Accept jaeger.thrift ofer compact thrift protocol
      - 6832:6832/udp # Accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # Serve configs
      - 16686:16686 # Serve frontend
      - 14268:14268 # Accept zipkin.thrift from zipkin senders