// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/event-private/main.proto

/*
Package eventprivate is a generated protocol buffer package.

It is generated from these files:
	proto/event-private/main.proto

It has these top-level messages:
	Event
	GetEventsRequest
	GetEventsResponse
	GetEventRequest
	GetEventResponse
	CreateEventRequest
	CreateEventResponse
	UpdateEventRequest
	UpdateEventResponse
	DeleteEventRequest
	DeleteEventResponse
*/
package eventprivate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: bson:"created_at"
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt int64 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
	// @inject_tag: bson:"start_date"
	StartDate int64 `protobuf:"varint,4,opt,name=start_date,json=startDate" json:"start_date,omitempty" bson:"start_date"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"uri"
	Uri string `protobuf:"bytes,6,opt,name=uri" json:"uri,omitempty" bson:"uri"`
	// @inject_tag: bson:"tags"
	Tags []string `protobuf:"bytes,7,rep,name=tags" json:"tags,omitempty" bson:"tags"`
	// @inject_tag: bson:"is_published"
	IsPublished bool `protobuf:"varint,8,opt,name=is_published,json=isPublished" json:"is_published,omitempty" bson:"is_published"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Event) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Event) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Event) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

type GetEventsRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *GetEventsRequest) Reset()                    { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()               {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetEventsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GetEventsResponse struct {
	Data []*Event `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *GetEventsResponse) Reset()                    { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()               {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetEventsResponse) GetData() []*Event {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetEventRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEventRequest) Reset()                    { *m = GetEventRequest{} }
func (m *GetEventRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEventRequest) ProtoMessage()               {}
func (*GetEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEventResponse struct {
	Data *Event `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetEventResponse) Reset()                    { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()               {}
func (*GetEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetEventResponse) GetData() *Event {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateEventRequest struct {
	Data *Event `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *CreateEventRequest) Reset()                    { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()               {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateEventRequest) GetData() *Event {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateEventResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Ok    bool   `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
}

func (m *CreateEventResponse) Reset()                    { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()               {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateEventResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UpdateEventRequest struct {
	Data *Event `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateEventRequest) Reset()                    { *m = UpdateEventRequest{} }
func (m *UpdateEventRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEventRequest) ProtoMessage()               {}
func (*UpdateEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateEventRequest) GetData() *Event {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateEventResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Ok    bool   `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
}

func (m *UpdateEventResponse) Reset()                    { *m = UpdateEventResponse{} }
func (m *UpdateEventResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateEventResponse) ProtoMessage()               {}
func (*UpdateEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateEventResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DeleteEventRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteEventRequest) Reset()                    { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()               {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteEventResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Ok    bool   `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
}

func (m *DeleteEventResponse) Reset()                    { *m = DeleteEventResponse{} }
func (m *DeleteEventResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteEventResponse) ProtoMessage()               {}
func (*DeleteEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteEventResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "eventprivate.Event")
	proto.RegisterType((*GetEventsRequest)(nil), "eventprivate.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "eventprivate.GetEventsResponse")
	proto.RegisterType((*GetEventRequest)(nil), "eventprivate.GetEventRequest")
	proto.RegisterType((*GetEventResponse)(nil), "eventprivate.GetEventResponse")
	proto.RegisterType((*CreateEventRequest)(nil), "eventprivate.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "eventprivate.CreateEventResponse")
	proto.RegisterType((*UpdateEventRequest)(nil), "eventprivate.UpdateEventRequest")
	proto.RegisterType((*UpdateEventResponse)(nil), "eventprivate.UpdateEventResponse")
	proto.RegisterType((*DeleteEventRequest)(nil), "eventprivate.DeleteEventRequest")
	proto.RegisterType((*DeleteEventResponse)(nil), "eventprivate.DeleteEventResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventService service

type EventServiceClient interface {
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := grpc.Invoke(ctx, "/eventprivate.EventService/GetEvents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := grpc.Invoke(ctx, "/eventprivate.EventService/GetEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := grpc.Invoke(ctx, "/eventprivate.EventService/CreateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error) {
	out := new(UpdateEventResponse)
	err := grpc.Invoke(ctx, "/eventprivate.EventService/UpdateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	out := new(DeleteEventResponse)
	err := grpc.Invoke(ctx, "/eventprivate.EventService/DeleteEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventService service

type EventServiceServer interface {
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventprivate.EventService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventprivate.EventService/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventprivate.EventService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventprivate.EventService/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventprivate.EventService/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventprivate.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvents",
			Handler:    _EventService_GetEvents_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/event-private/main.proto",
}

func init() { proto.RegisterFile("proto/event-private/main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x7e, 0x8c, 0xf6, 0xa4, 0xa2, 0xdb, 0x69, 0x11, 0xa1, 0x62, 0x5d, 0x1a, 0x21,
	0x11, 0x4d, 0xa2, 0x11, 0xe5, 0x8e, 0xc1, 0x05, 0x62, 0x88, 0x5b, 0x14, 0xc4, 0x75, 0x71, 0x17,
	0xab, 0x58, 0xed, 0xe2, 0xcc, 0x76, 0x2a, 0x21, 0xb4, 0x1b, 0x5e, 0x81, 0x27, 0xe0, 0x91, 0x10,
	0xaf, 0xc0, 0x83, 0x20, 0x3b, 0x09, 0x4b, 0xd2, 0x6e, 0x62, 0xbb, 0x73, 0xce, 0xff, 0xef, 0xf3,
	0xf3, 0xf9, 0x68, 0x61, 0x9c, 0x08, 0xae, 0x78, 0x40, 0x37, 0x34, 0x56, 0xcf, 0x12, 0xc1, 0x36,
	0x44, 0xd1, 0xe0, 0x9c, 0xb0, 0x78, 0x6a, 0x04, 0xec, 0x19, 0x25, 0x17, 0x46, 0x8f, 0x97, 0x9c,
	0x2f, 0xd7, 0x34, 0x20, 0x09, 0x0b, 0x48, 0x1c, 0x73, 0x45, 0x14, 0xe3, 0xb1, 0xcc, 0xbc, 0xde,
	0x2f, 0x0b, 0xda, 0xef, 0xb4, 0x1d, 0xef, 0x43, 0x83, 0x45, 0x8e, 0xe5, 0x5a, 0x7e, 0x37, 0x6c,
	0xb0, 0x08, 0x0f, 0x01, 0xce, 0x04, 0x25, 0x8a, 0x46, 0x73, 0xa2, 0x9c, 0x86, 0x6b, 0xf9, 0xcd,
	0xb0, 0x9b, 0x47, 0xde, 0x28, 0x2d, 0xa7, 0x49, 0x54, 0xc8, 0xcd, 0x4c, 0xce, 0x23, 0x99, 0x2c,
	0x15, 0x11, 0x6a, 0xae, 0x03, 0x4e, 0x2b, 0x93, 0x4d, 0xe4, 0x94, 0x28, 0x8a, 0x08, 0xad, 0x98,
	0x9c, 0x53, 0xa7, 0x6d, 0x70, 0xe6, 0x8c, 0xfb, 0xd0, 0x4c, 0x05, 0x73, 0xf6, 0x4c, 0x48, 0x1f,
	0xb5, 0x4b, 0x91, 0xa5, 0x74, 0xee, 0xb9, 0x4d, 0xed, 0xd2, 0x67, 0x9c, 0x40, 0x8f, 0xc9, 0x79,
	0x92, 0x2e, 0xd6, 0x4c, 0x7e, 0xa1, 0x91, 0xd3, 0x71, 0x2d, 0xbf, 0x13, 0xda, 0x4c, 0x7e, 0x28,
	0x42, 0x9e, 0x0f, 0xfb, 0xef, 0xa9, 0x32, 0x55, 0xc9, 0x90, 0x5e, 0xa4, 0x54, 0x2a, 0x1c, 0x42,
	0xfb, 0x22, 0xa5, 0xe2, 0x6b, 0x5e, 0x60, 0xf6, 0xe1, 0xbd, 0x82, 0x83, 0x92, 0x53, 0x26, 0x3c,
	0x96, 0x14, 0x9f, 0x42, 0x2b, 0x22, 0x8a, 0x38, 0x96, 0xdb, 0xf4, 0xed, 0xd9, 0x60, 0x5a, 0xee,
	0xe6, 0xd4, 0x78, 0x43, 0x63, 0xf0, 0x26, 0xd0, 0x2f, 0x6e, 0x17, 0x98, 0x5a, 0x13, 0xbd, 0x93,
	0xab, 0xa7, 0xec, 0xc8, 0x6f, 0xdd, 0x9c, 0xff, 0x35, 0xe0, 0x5b, 0xd3, 0xef, 0x0a, 0xe2, 0xbf,
	0xaf, 0x9f, 0xc0, 0xa0, 0x72, 0x3d, 0xc7, 0x0f, 0xa1, 0x4d, 0x85, 0xe0, 0xa2, 0xe8, 0x84, 0xf9,
	0xd0, 0x0f, 0xe7, 0x2b, 0x33, 0xe5, 0x4e, 0xd8, 0xe0, 0x2b, 0xcd, 0xfe, 0x64, 0x86, 0x79, 0x67,
	0x76, 0xe5, 0xfa, 0xad, 0xd8, 0x4f, 0x00, 0x4f, 0xe9, 0x9a, 0xd6, 0xd8, 0xdb, 0xad, 0x1d, 0x54,
	0x5c, 0xb7, 0x41, 0xcc, 0x7e, 0xb6, 0xa0, 0x67, 0xee, 0x7d, 0xa4, 0x62, 0xc3, 0xce, 0x28, 0x7e,
	0x86, 0xee, 0xbf, 0x4d, 0xc0, 0x71, 0xb5, 0xb0, 0xfa, 0x32, 0x8d, 0x8e, 0xae, 0xd5, 0xb3, 0x47,
	0x78, 0xf8, 0xfd, 0xf7, 0x9f, 0x1f, 0x8d, 0x1e, 0x42, 0xb0, 0x79, 0x9e, 0xfd, 0x4e, 0x25, 0x2e,
	0xa0, 0x53, 0x18, 0xf1, 0x70, 0x77, 0x82, 0x22, 0xff, 0xf8, 0x3a, 0x39, 0x4f, 0xff, 0xd0, 0xa4,
	0x3f, 0xc0, 0xfe, 0x55, 0xfa, 0xe0, 0x1b, 0x8b, 0x2e, 0x91, 0x81, 0x5d, 0x1a, 0x39, 0xba, 0xd5,
	0x3c, 0xdb, 0xcb, 0x34, 0x9a, 0xdc, 0xe0, 0xc8, 0x61, 0x0f, 0x0c, 0xac, 0xef, 0x95, 0x6a, 0x79,
	0x69, 0x1d, 0xa3, 0x04, 0xbb, 0x34, 0xe1, 0x3a, 0x6a, 0x7b, 0x77, 0xea, 0xa8, 0x1d, 0xeb, 0xe1,
	0x1d, 0x19, 0xd4, 0xa3, 0xd9, 0xb0, 0x5c, 0x97, 0xde, 0xa7, 0x29, 0x8b, 0x2e, 0x35, 0x74, 0x05,
	0x76, 0x69, 0xe6, 0x75, 0xe8, 0xf6, 0xd2, 0xd4, 0xa1, 0x3b, 0x16, 0xa6, 0x68, 0xe6, 0x71, 0xbd,
	0x99, 0x8b, 0x3d, 0xf3, 0x0f, 0xf9, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xb0, 0x38,
	0x3a, 0x6f, 0x05, 0x00, 0x00,
}
